script: "bundle exec rake test"
bundler_args: "--no-deployment"
cache: bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1.5
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
